<!DOCTYPE html>
<?php

if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    // die($this->basePath());
}
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
<!--    <link rel="shortcut icon" href="images/icon.png">-->

    <title>EArzeh</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href='<?php echo $this->basePath() . '/assets/layout/js/bootstrap/dist/css/bootstrap.css'?>' rel='stylesheet' type='text/css'>
    <link href='<?php echo $this->basePath() . '/assets/layout/fonts/font-awesome-4/css/font-awesome.min.css'?>' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <link href='<?php echo $this->basePath() . '/assets/layout/../../assets/js/html5shiv.js'?>' rel='stylesheet' type='text/css'>
    <link href='<?php echo $this->basePath() . '/assets/layout/../../assets/js/respond.min.js'?>' rel='stylesheet' type='text/css'>

    <![endif]-->

    <link href='<?php echo $this->basePath() . '/assets/layout/js/jquery.nanoscroller/nanoscroller.css'?>' rel='stylesheet' type='text/css'>
    <link href='<?php echo $this->basePath() . "/assets/layout/css/$this->lang/style.css"?>' rel='stylesheet' type='text/css'>

    <?php echo
        $this->headLink();
        $this->headLink()->deleteContainer();
    ?>
</head>
<body>

<div id="cl-wrapper">

    <div class="cl-sidebar">
        <div class="cl-toggle"><i class="fa fa-bars"></i></div>
        <div class="cl-navblock">
            <div class="menu-space">
                <div class="content">
                    <div class="sidebar-logo">
                        <div class="logo">
                            <a href="index2.html"></a>
                        </div>
                    </div>
                    <div class="side-user">
                        <div class="avatar"><img style="width: 100px" src="<?php echo $this->basePath()?>/assets/layout/images/ea.png" alt="Avatar" /></div>
                    </div>
                    <ul class="cl-vnavigation">
                        <li class="active" ><a href="<?php echo $this->url('home',['lang' => $this->lang]); ?>"><i class="fa fa-home"></i><span><?php echo $this->translate('Dashboard') ?></span></a></li>
                        <?php
                            $this->navigation('Navigation')->menu()->setPartial(array('nav/menu' ,'default'));
                            echo $this->navigation('Navigation')->menu()->render();
                        ?>
                    </ul>
                </div>
            </div>
            <div class="text-right collapse-button" style="padding:7px 9px;">
                <input type="text" class="form-control search" placeholder="Search..." />
                <button id="sidebar-collapse" class="btn btn-default" style=""><i style="color:#fff;" class="fa fa-angle-left"></i></button>
            </div>
        </div>
    </div>


    <div class="container-fluid" id="pcont">
        <!-- TOP NAVBAR -->
        <div id="head-nav" class="navbar navbar-default" style="width: 100%">
            <div class="container-fluid">
                <div class="navbar-collapse">
                    <ul class="nav navbar-nav navbar-right user-nav">
                        <li class="dropdown profile_menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span><?php echo $this->translate('Default Language') ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('home', array('lang' => $this->lang,'controller' => 'Application\Controller\Index','action' => 'lang', 'id'=>'en')); ?>"><?php echo $this->translate('English') ?></a></li>
                                <li><a href="<?php echo $this->url('home', array('lang' => $this->lang,'controller' => 'Application\Controller\Index','action' => 'lang', 'id'=>'fa')); ?>"><?php echo $this->translate('Persian') ?></a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right user-nav">
                        <li class="dropdown profile_menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img style="width: 100px" src="<?php echo $this->basePath()?>/assets/layout/images/ea.png" alt="Avatar" />
                                <span><?php echo $this->username ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#"><?php echo $this->translate('Profile') ?></a></li>
                                <li><a href="#"><?php echo $this->translate('Messages') ?></a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('user', array('action' => 'logout')); ?>"><?php echo $this->translate('Sign Out') ?></a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav not-nav">
                        <li class="button dropdown">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class=" fa fa-inbox"></i></a>
                            <ul class="dropdown-menu messages">
                                <li>
                                    <div class="nano nscroller">
                                        <div class="content">
                                            <ul>
                                                <li>
                                                    <a href="#">
                                                        <img src="<?php echo $this->basePath()?>/assets/layout/images/avatar2.jpg" alt="avatar" /><span class="date pull-right">13 Sept.</span> <span class="name">Daniel</span> Hey! How are you?
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <img src="<?php echo $this->basePath()?>/assets/layout/images/avatar_50.jpg" alt="avatar" /><span class="date pull-right">20 Oct.</span><span class="name">Adam</span> Hi! Can you fix my phone?
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <img src="<?php echo $this->basePath()?>/assets/layout/images/avatar4_50.jpg" alt="avatar" /><span class="date pull-right">2 Nov.</span><span class="name">Michael</span> Regards!
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <ul class="foot"><li><a href="#">View all messages </a></li></ul>
                                </li>
                            </ul>
                        </li>
                        <li class="button dropdown">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe"></i><span class="bubble">2</span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="nano nscroller">
                                        <div class="content">
                                            <ul>
                                                <li><a href="#"><i class="fa fa-cloud-upload info"></i><b>Daniel</b> is now following you <span class="date">2 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-male success"></i> <b>Michael</b> commented on your link <span class="date">15 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-bug warning"></i> <b>Mia</b> commented on post <span class="date">30 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-credit-card danger"></i> <b>Andrew</b> sent you a request <span class="date">1 hour ago.</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <ul class="foot"><li><a href="#">View all activity </a></li></ul>
                                </li>
                            </ul>
                        </li>

                    </ul>

                </div><!--/.nav-collapse animate-collapse -->
            </div>
        </div>


        <div class="cl-mcont">
            <?php if(isset($this->message)): ?>
            <div class="alert alert-<?php echo $this->message['type'] ?>">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <i class="fa fa-info-circle sign"></i><strong></strong> <?php echo $this->message['content'] ?>
            </div>
            <?php endif; ?>
            <?php echo $this->content; ?>
        </div>
    </div>

</div>


<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.cookie/jquery.cookie.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.pushmenu/js/jPushMenu.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.nanoscroller/jquery.nanoscroller.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.sparkline/jquery.sparkline.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/jquery.ui/jquery-ui.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/behaviour/core.js' ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/behaviour/dashboard.js' ?>"></script>


<!-- Bootstrap core JavaScript================================================== -->
<!-- Placed at the end of the document so the pages load faster -->



<script type="text/javascript" src="<?php echo $this->basePath() . '/assets/layout/js/bootstrap/dist/js/bootstrap.min.js' ?>"></script>

<?php
echo $this->headScript()

    ->appendFile($this->basePath() . '/assets/layout/js/jquery.datatables/jquery.datatables.min.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.datatables/bootstrap-adapter/js/datatables.js')
;
$this->headScript()->deleteContainer();

?>



</body>
</html>