<div class="row">
    <div class="row">
        <div class="col-md-12">
<!--            <div class="block-flat">-->
<!--                <div class="header">-->
<!--                    <h3>پیام مدیریت</h3>-->
<!--                </div>-->
<!--                <div class="content">-->
<!--                   <p style="direction: rtl">-->
<!--                       به پنل مدیریت خوش آمدید-->
<!--                   </p>-->
<!--                    <p style="direction: rtl">-->
<!--                        این پنل بخش مدیریت سایت است که قالبیت مدیریت کاربران و مدیریت سرویس ها می باشد. صفحه ای که مشاهده می کنید صفحه ی پیشخوان است که در آن گزارشات لازم قرار خواهد گرفت. در این نسخه که برای شما آماده شده است به دلیل عدم وجود گزارشات المان های گرافیکی به صورت تست قرار گرفته است. همچنین بخش های دیگر که همچنان در حال ساخت می باشد اطلاعات به صورت تست قرار گرفته است تا بخش های کارکردی آن نیز آماده شود.-->
<!--                        در این سیستم ۳نوع کاربر فعالیت می کنند که شامل مدیر , اپراتور و کمپانی ها می باشد.-->
<!--                        در این نسخه بخش فرایند مدیریت کاربران کامل شده و در صورت تهیه پنل پیامک و میل سرور ارسال اس ام اس و میل نیز انجام خواهد شد.این بخش فقط برای کاربر مدیر قابل دسترس است.ضمنا تقاضا می شود فیلدهایی که مد نظر دارید که در مدیریت کاربران قرار بگیرد در اختیار ما بگذارید.-->
<!--                        بخش مدیریت سرویس ها نیز آماده شده وآماده برای وارد کردن اطلاعات می باشد.این بخش فقط برای کاربر مدیر قابل دسترس است.-->
<!--                        بخش B2b بخشی است که برای کمپانی ها قابل دسترس است که می توانند عرضه ها و تقاضاهای خود را وارد کنند. واسط کاربری این بخش در حال طراحی می باشد.در قسمت لیست درخواست ها کاربر کمپانی می تواند وضعیت در خواست خود را مشاهد کند و ببیند کدام اپراتور در حال بررسی آن می باشد.-->
<!--                        بخش مدیریت حساب کاربری .کاربران می توانند اطلاعات اضافی ای که سیستم خواسته را تکمیل نمایند که برای این بخش منتظر اعلام شما هستیم.-->
<!---->
<!--                    </p>-->
<!--                </div>-->
<!--            </div>-->

<!--            <div class="block-flat">-->
<!--                <div class="header">-->
<!--                    <h3>وضعیت درخواست ها</h3>-->
<!--                </div>-->
<!--                <div class="content">-->
<!--                    <div class="table-responsive">-->
<!--                        <table class="no-border hover list">-->
<!--                            <tbody class="no-border-y">-->
<!--                            <tr class="items">-->
<!--                                <td style="width: 10%;"><span class="label label-warning">در حال بررسی</span></td>-->
<!--                                <td><p><strong></strong><span></span></p></td>-->
<!--                                <td class="color-success"><div class="progress"><div class="progress-bar progress-bar-warning" style="width: 80%">80%</div></div></td>-->
<!--                                <td class="text-right" style="width: 15%;"><a class="label label-default" href="#"><i class="fa fa-pencil"></i></a> <a class="label label-danger" href="#"><i class="fa fa-times"></i></a></td>-->
<!--                            </tr>-->
<!--                            <tr class="items">-->
<!--                                <td><span class="label label-danger">بررسی نشده</span></td>-->
<!--                                <td><p><strong></strong><span></span></p></td>-->
<!--                                <td class="color-success"><div class="progress"><div class="progress-bar progress-bar-danger" style="width: 60%">60%</div></div></td>-->
<!--                                <td class="text-right"><a class="label label-default" href="#"><i class="fa fa-pencil"></i></a> <a class="label label-danger" href="#"><i class="fa fa-times"></i></a></td>-->
<!--                            </tr>-->
<!--                            <tr class="items">-->
<!--                                <td><span class="label label-success">بررسی شده</span></td>-->
<!--                                <td><p><strong></strong><span></span></p></td>-->
<!--                                <td class="color-success"><div class="progress"><div class="progress-bar progress-bar-success" style="width: 100%">100%</div></div></td>-->
<!--                                <td class="text-right"><a class="label label-default" href="#"><i class="fa fa-pencil"></i></a> <a class="label label-danger" href="#"><i class="fa fa-times"></i></a></td>-->
<!--                            </tr>-->
<!--                            </tbody>-->
<!--                        </table>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->

        </div>
    </div>

    <div class="col-md-3 col-sm-6">
        <div class="fd-tile detail tile-green">
            <div class="content"><h1 class="text-left">170</h1><p>درخواست های خرید</p></div>
            <div class="icon"><i class="fa fa-flag"></i></div>
            <a class="details" href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'b2b' ,'action' => 'index','id' => 'buy']); ?>">Details <span><i class="fa fa-arrow-circle-right pull-right"></i></span></a>
        </div>
    </div>


    <div class="col-md-3 col-sm-6">
        <div class="fd-tile detail tile-red">
            <div class="content"><h1 class="text-left">24</h1><p>درخواست های فروش</p></div>
            <div class="icon"><i class="fa fa-comments"></i></div>
            <a class="details" href="<?php echo $this->url('user',['lang' => $this->lang,'controller' => 'b2b' ,'action' => 'index','id' => 'sell']); ?>">Details <span><i class="fa fa-arrow-circle-right pull-right"></i></span></a>
        </div>
    </div>



</div>

